data_dir: genbanks/
db_name: /students/2024-2025/master/jgray/genbank.db
sql_script: src/create_tables.sql
# Initialize new database (Old database has to be deleted if True)
init: False
# Multi insert amount of records to be submitted
batch_size: 3000